spring:
  datasource:
    url: jdbc:h2:~/test;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:

logging:
  level:
    root: warn
    com.example: info
#    org.hibernate: warn
#    org.springframework: info
#    org.springframework.boot.web: warn
#    org.springframework.web: warn
#    org.springframework.data: warn

