spring:
  datasource:
    url: jdbc:h2:~/test;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: none

logging:
  level:
    root: info
    com.example: info
    org.hibernate.cfg: info
    org.hibernate.SQL: debug
#    org.springframework: info
#    org.springframework.boot.web: warn
#    org.springframework.web: warn
#    org.springframework.data: warn

