spring:
  datasource:
    url: jdbc:h2:~/test;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:

logging:
  level:
    root: info
    org.hibernate: info
    org.springframework: info
    org.springframework.data: info
